version: '3.2'
services: 
  web:
    restart: always
    build: .
    volumes: 
      - ./app/back-end:/var/www/
    depends_on: 
      - db

  db:
    image: postgres:14.0-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: coroas
    ports:
      - "5432:5432"
    volumes: 
    - ./.docker/db:/var/lib/postgresql
  
  nginx:
    build: ./.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes: 
      - ./app/back-end:/var/www
    depends_on: 
      - web

